export const CATEGORIES_TRANSLATED = {
  american_restaurant: '미국 음식',
  asian_restaurant: '아시아 음식',
  barbecue_restaurant: '바비큐',
  brazilian_restaurant: '브라질 음식',
  breakfast_restaurant: '아침식사',
  brunch_restaurant: '브런치',
  chinese_restaurant: '중식',
  fast_food_restaurant: '패스트푸드',
  french_restaurant: '프랑스 음식',
  greek_restaurant: '그리스 음식',
  hamburger_restaurant: '햄버거',
  ice_cream_shop: '아이스크림',
  indian_restaurant: '인도 음식',
  indonesian_restaurant: '인도네시아 음식',
  italian_restaurant: '이탈리아 음식',
  japanese_restaurant: '일식',
  korean_restaurant: '한식',
  lebanese_restaurant: '레바논 음식',
  meal_delivery: '배달',
  meal_takeaway: '테이크아웃',
  mediterranean_restaurant: '지중해 음식',
  mexican_restaurant: '멕시코 음식',
  middle_eastern_restaurant: '중동 음식',
  pizza_restaurant: '피자',
  ramen_restaurant: '라멘',
  restaurant: '음식점',
  sandwich_shop: '샌드위치',
  seafood_restaurant: '해산물',
  spanish_restaurant: '스페인 음식',
  steak_house: '스테이크',
  sushi_restaurant: '초밥',
  thai_restaurant: '태국 음식',
  turkish_restaurant: '터키 음식',
  vegan_restaurant: '비건',
  vegetarian_restaurant: '채식',
  vietnamese_restaurant: '베트남 음식',
  cafe: '카페',
  coffee_shop: '커피숍',
  bakery: '베이커리',
  bar: '술집',
  auto_parts_store: '자동차부품',
  bicycle_store: '자전거',
  book_store: '서점',
  cell_phone_store: '휴대폰',
  clothing_store: '의류',
  convenience_store: '편의점',
  department_store: '백화점',
  discount_store: '할인',
  electronics_store: '전자제품',
  florist: '꽃집',
  furniture_store: '가구',
  gift_shop: '선물',
  grocery_store: '식료품',
  hardware_store: '철물',
  home_goods_store: '가정용품',
  home_improvement_store: '인테리어',
  jewelry_store: '보석',
  liquor_store: '주류',
  market: '시장',
  pet_store: '애완동물',
  shoe_store: '신발',
  shopping_mall: '쇼핑몰',
  sporting_goods_store: '스포츠용품',
  store: '상점',
  supermarket: '마트',
  wholesaler: '도매',
  bed_and_breakfast: '민박',
  campground: '캠핑장',
  camping_cabin: '캠핑용 통나무집',
  cottage: '별장',
  extended_stay_hotel: '장기숙박호텔',
  farmstay: '농장숙박',
  guest_house: '게스트하우스',
  hostel: '호스텔',
  hotel: '호텔',
  lodging: '숙박',
  motel: '모텔',
  private_guest_room: '개인실',
  resort_hotel: '리조트',
  rv_park: '캠핑카공원',
  amusement_center: '오락실',
  amusement_park: '놀이공원',
  aquarium: '수족관',
  art_gallery: '미술관',
  banquet_hall: '연회장',
  bowling_alley: '볼링장',
  casino: '카지노',
  community_center: '커뮤니티센터',
  convention_center: '컨벤션센터',
  cultural_center: '문화센터',
  event_venue: '행사장',
  hiking_area: '하이킹',
  historical_landmark: '역사유적지',
  library: '도서관',
  movie_rental: '영화대여',
  movie_theater: '영화관',
  museum: '박물관',
  national_park: '국립공원',
  night_club: '클럽',
  park: '공원',
  performing_arts_theater: '공연장',
  tourist_attraction: '관광명소',
  visitor_center: '관광안내소',
  wedding_venue: '결혼식장',
  zoo: '동물원',
};
